name: Deploy to Netlify

on:
  push:
    branches:
      - main  # Change this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Specify the Node.js version you need

    - name: Install dependencies
      run: |
        cd client
        npm ci  # Prefer npm ci for CI environments

    - name: Build the project
      run: |
        cd client
        npm run build

    - name: Deploy to Netlify
      uses: nwtgck/actions-netlify@v1.2.3
      with:
        publish-dir: client/build
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        netlify-site-id: ${{ secrets.NETLIFY_SITE_ID }}
